include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true         # nul-safe + cast explicite
    strict-inference: true
  exclude:                     # ignore les fichiers générés
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"

linter:
  rules:
    # --- Ajouts « qualité » 2025 ---
    - unreachable_from_main   # détection code mort
    - prefer_final_locals
    - prefer_final_in_for_each
    - use_setters_to_change_properties
    - unnecessary_async
    - avoid_print            # impose logger
    - always_use_package_imports

formatter:                     # Nouveauté Dart 3.7/3.8
  page_width: 100             # largeur max pour dart format (ex. 100)