coverage:
  precision: 2
  range: "40..90"
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: 70
  ignore:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
    - "lib/**/generated/**"
    - "build/**"
