default_platform(:ios)

platform :ios do
  desc "Build and sign IPA for Firebase App Distribution"
  lane :build_and_sign do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      in_house: false
    )

    build_app(
      scheme: "Runner",
      export_method: "ad-hoc",
      api_key: api_key
    )
  end
end
