name: Mobile CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze-test:
    name: Analyze • Format • Test • Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          # utile pour lcov & sonar

      # 2. Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          cache: true

      # 3. Secrets → .env (nécessaire aux tests qui lisent .env)
      - run: echo "${{ secrets.ENV_FILE }}" > .env

      # 4. Dependencies
      - name: Install pub dependencies
        run: flutter pub get

      # 5. Codegen (Riverpod / Freezed)
      - run: dart run build_runner build --delete-conflicting-outputs

      # 6. Format check
      - name: Check code formatted
        run: dart format --set-exit-if-changed .

      # 7. Lint & static analysis (fatal)
      - name: Static analysis
        run: flutter analyze --fatal-warnings --fatal-infos

      # 8. Tests + coverage
      - name: Run tests with coverage
        run: |
          flutter test --coverage
          if [ -s coverage/lcov.info ]; then
            genhtml coverage/lcov.info --output-directory coverage/html
          else
            echo "⚠️  No coverage data generated (no tests)."
          fi

      # 9. Upload coverage artefacts
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage/html

###### ——— Security scan (CodeQL) ——— ######
codeql:
  name: CodeQL Static Analysis
  runs-on: ubuntu-latest
  if: github.repository_visibility == 'public'   # ← ignore si privé sans GA Security
  permissions:
    actions: read
    contents: read
    security-events: write   # indispensable pour publier le rapport SARIF
  steps:
    - uses: actions/checkout@v4

    # 1. Init CodeQL pour Dart (langage en preview)
    - uses: github/codeql-action/init@v3
      with:
        languages: dart


    # 2. « Autobuild » — inutile pour Dart, mais l’étape attend quand même un build
    - name: Dummy build
      run: echo "No build step required for Dart projects"

    # 3. Analyse + upload SARIF
    - uses: github/codeql-action/analyze@v3