name: Mobile CI

on:
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  analyze-test:
    name: Analyze, Test & Lint (recette)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter with cache
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          cache: true

      - name: Create .env from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Generate riverpod & freezed code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze code (erreurs seulement)
        run: flutter analyze

      - name: Run tests (recette)
        run: flutter test