name: Mobile CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze-test:
    name: Analyze • Format • Test • Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          # utile pour lcov & sonar

      # 2. Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          cache: true

      # 3. Secrets → .env (nécessaire aux tests qui lisent .env)
      - run: echo "${{ secrets.ENV_FILE }}" > .env

      # 4. Dependencies
      - name: Install pub dependencies
        run: flutter pub get

      # 5. Codegen (Riverpod / Freezed)
      - run: dart run build_runner build --delete-conflicting-outputs

      # 6. Lint & static analysis (fatal)
      - name: Static analysis
        run: flutter analyze --fatal-warnings --fatal-infos

      # 7. Tests + coverage
      - name: Run tests & clean coverage
        run: |
          flutter test --coverage
          lcov --remove coverage/lcov.info \
               $(grep -vE '^\s*$|^\s*#' .lcov_exclude) \
               --output coverage/clean.info \
               --ignore-errors unused
          genhtml coverage/clean.info -o coverage/html

      # 8. Upload coverage artefacts
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage/html