name: iOS Release CD

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  release-ios:
    name: Release IPA on Firebase App Distribution
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Create .env from secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Generate riverpod & freezed code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build IPA (no-sign)
        run: flutter build ipa --release --no-codesign

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          path: build/ios/ipa/*.ipa

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Upload IPA to Firebase App Distribution
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}' > ${HOME}/firebase_key.json
          firebase auth:login:ci --token "$(cat ${HOME}/firebase_key.json)"
          firebase appdistribution:distribute build/ios/ipa/*.ipa \
            --app ${{ secrets.FIREBASE_APP_ID_IOS }} \
            --release-notes "New AthleteIQ IPA build via GitHub Actions" \
            --groups "testers"
